name: Build APK

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - name: Create secret_key.dart
        run: echo "const openApiHost = '${{ secrets.OPEN_API_HOST }}';" > packages/core_data/lib/api/secret_key.dart
      - name: Install Melos
        run: dart pub global activate melos
      - name: Bootstrap Melos
        run: dart pub global run melos bootstrap
      - name: Build APK
        run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - name: Create secret_key.dart
        run: echo "const openApiHost = '${{ secrets.OPEN_API_HOST }}';" > packages/core_data/lib/api/secret_key.dart
      - name: Install Melos
        run: dart pub global activate melos
      - name: Bootstrap Melos
        run: dart pub global run melos bootstrap
      - name: Format check
        run: dart pub global run melos run format:check
      - name: Analyze
        run: dart pub global run melos run analyze
      - name: Test
        run: dart pub global run melos run test
        if: always()