name: Dart CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Melos
      run: dart pub global activate melos

    - name: Bootstrap Melos
      run: melos bootstrap

    - name: Format check
      run: melos run format:check

    - name: Analyze
      run: melos run analyze

    - name: Test
      run: melos run test
